/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CakePreorderRouteImport } from './routes/cake-preorder'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CatalogSlugRouteImport } from './routes/catalog_.$slug'
import { Route as KkIndexRouteImport } from './routes/kk.index'
import { Route as KkAboutRouteImport } from './routes/kk.about'
import { Route as KkCakePreorderRouteImport } from './routes/kk.cake-preorder'
import { Route as KkCareerRouteImport } from './routes/kk.career'
import { Route as KkCatalogRouteImport } from './routes/kk.catalog'
import { Route as KkCateringRouteImport } from './routes/kk.catering'
import { Route as KkContactsRouteImport } from './routes/kk.contacts'
import { Route as KkNewsRouteImport } from './routes/kk.news'
import { Route as KkPrivacyRouteImport } from './routes/kk.privacy'
import { Route as KkPromotionsRouteImport } from './routes/kk.promotions'
import { Route as KkStoresRouteImport } from './routes/kk.stores'
import { Route as KkTermsRouteImport } from './routes/kk.terms'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as PromotionsSlugRouteImport } from './routes/promotions_.$slug'
import { Route as KkCatalogSlugRouteImport } from './routes/kk.catalog_.$slug'
import { Route as KkNewsSlugRouteImport } from './routes/kk.news_.$slug'
import { Route as KkPromotionsSlugRouteImport } from './routes/kk.promotions_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CakePreorderRoute = CakePreorderRouteImport.update({
  id: '/cake-preorder',
  path: '/cake-preorder',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog_/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KkIndexRoute = KkIndexRouteImport.update({
  id: '/kk/',
  path: '/kk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KkAboutRoute = KkAboutRouteImport.update({
  id: '/kk/about',
  path: '/kk/about',
  getParentRoute: () => rootRouteImport,
} as any)
const KkCakePreorderRoute = KkCakePreorderRouteImport.update({
  id: '/kk/cake-preorder',
  path: '/kk/cake-preorder',
  getParentRoute: () => rootRouteImport,
} as any)
const KkCareerRoute = KkCareerRouteImport.update({
  id: '/kk/career',
  path: '/kk/career',
  getParentRoute: () => rootRouteImport,
} as any)
const KkCatalogRoute = KkCatalogRouteImport.update({
  id: '/kk/catalog',
  path: '/kk/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KkCateringRoute = KkCateringRouteImport.update({
  id: '/kk/catering',
  path: '/kk/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const KkContactsRoute = KkContactsRouteImport.update({
  id: '/kk/contacts',
  path: '/kk/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const KkNewsRoute = KkNewsRouteImport.update({
  id: '/kk/news',
  path: '/kk/news',
  getParentRoute: () => rootRouteImport,
} as any)
const KkPrivacyRoute = KkPrivacyRouteImport.update({
  id: '/kk/privacy',
  path: '/kk/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KkPromotionsRoute = KkPromotionsRouteImport.update({
  id: '/kk/promotions',
  path: '/kk/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const KkStoresRoute = KkStoresRouteImport.update({
  id: '/kk/stores',
  path: '/kk/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const KkTermsRoute = KkTermsRouteImport.update({
  id: '/kk/terms',
  path: '/kk/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsSlugRoute = PromotionsSlugRouteImport.update({
  id: '/promotions_/$slug',
  path: '/promotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KkCatalogSlugRoute = KkCatalogSlugRouteImport.update({
  id: '/kk/catalog_/$slug',
  path: '/kk/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KkNewsSlugRoute = KkNewsSlugRouteImport.update({
  id: '/kk/news_/$slug',
  path: '/kk/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KkPromotionsSlugRoute = KkPromotionsSlugRouteImport.update({
  id: '/kk/promotions_/$slug',
  path: '/kk/promotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cake-preorder': typeof CakePreorderRoute
  '/career': typeof CareerRoute
  '/catalog': typeof CatalogRoute
  '/catering': typeof CateringRoute
  '/contacts': typeof ContactsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/kk/about': typeof KkAboutRoute
  '/kk/cake-preorder': typeof KkCakePreorderRoute
  '/kk/career': typeof KkCareerRoute
  '/kk/catalog': typeof KkCatalogRoute
  '/kk/catering': typeof KkCateringRoute
  '/kk/contacts': typeof KkContactsRoute
  '/kk/news': typeof KkNewsRoute
  '/kk/privacy': typeof KkPrivacyRoute
  '/kk/promotions': typeof KkPromotionsRoute
  '/kk/stores': typeof KkStoresRoute
  '/kk/terms': typeof KkTermsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/kk/': typeof KkIndexRoute
  '/kk/catalog/$slug': typeof KkCatalogSlugRoute
  '/kk/news/$slug': typeof KkNewsSlugRoute
  '/kk/promotions/$slug': typeof KkPromotionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cake-preorder': typeof CakePreorderRoute
  '/career': typeof CareerRoute
  '/catalog': typeof CatalogRoute
  '/catering': typeof CateringRoute
  '/contacts': typeof ContactsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/kk/about': typeof KkAboutRoute
  '/kk/cake-preorder': typeof KkCakePreorderRoute
  '/kk/career': typeof KkCareerRoute
  '/kk/catalog': typeof KkCatalogRoute
  '/kk/catering': typeof KkCateringRoute
  '/kk/contacts': typeof KkContactsRoute
  '/kk/news': typeof KkNewsRoute
  '/kk/privacy': typeof KkPrivacyRoute
  '/kk/promotions': typeof KkPromotionsRoute
  '/kk/stores': typeof KkStoresRoute
  '/kk/terms': typeof KkTermsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/kk': typeof KkIndexRoute
  '/kk/catalog/$slug': typeof KkCatalogSlugRoute
  '/kk/news/$slug': typeof KkNewsSlugRoute
  '/kk/promotions/$slug': typeof KkPromotionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cake-preorder': typeof CakePreorderRoute
  '/career': typeof CareerRoute
  '/catalog': typeof CatalogRoute
  '/catering': typeof CateringRoute
  '/contacts': typeof ContactsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/catalog_/$slug': typeof CatalogSlugRoute
  '/kk/about': typeof KkAboutRoute
  '/kk/cake-preorder': typeof KkCakePreorderRoute
  '/kk/career': typeof KkCareerRoute
  '/kk/catalog': typeof KkCatalogRoute
  '/kk/catering': typeof KkCateringRoute
  '/kk/contacts': typeof KkContactsRoute
  '/kk/news': typeof KkNewsRoute
  '/kk/privacy': typeof KkPrivacyRoute
  '/kk/promotions': typeof KkPromotionsRoute
  '/kk/stores': typeof KkStoresRoute
  '/kk/terms': typeof KkTermsRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/promotions_/$slug': typeof PromotionsSlugRoute
  '/kk/': typeof KkIndexRoute
  '/kk/catalog_/$slug': typeof KkCatalogSlugRoute
  '/kk/news_/$slug': typeof KkNewsSlugRoute
  '/kk/promotions_/$slug': typeof KkPromotionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cake-preorder'
    | '/career'
    | '/catalog'
    | '/catering'
    | '/contacts'
    | '/news'
    | '/privacy'
    | '/promotions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stores'
    | '/terms'
    | '/catalog/$slug'
    | '/kk/about'
    | '/kk/cake-preorder'
    | '/kk/career'
    | '/kk/catalog'
    | '/kk/catering'
    | '/kk/contacts'
    | '/kk/news'
    | '/kk/privacy'
    | '/kk/promotions'
    | '/kk/stores'
    | '/kk/terms'
    | '/news/$slug'
    | '/promotions/$slug'
    | '/kk/'
    | '/kk/catalog/$slug'
    | '/kk/news/$slug'
    | '/kk/promotions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cake-preorder'
    | '/career'
    | '/catalog'
    | '/catering'
    | '/contacts'
    | '/news'
    | '/privacy'
    | '/promotions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stores'
    | '/terms'
    | '/catalog/$slug'
    | '/kk/about'
    | '/kk/cake-preorder'
    | '/kk/career'
    | '/kk/catalog'
    | '/kk/catering'
    | '/kk/contacts'
    | '/kk/news'
    | '/kk/privacy'
    | '/kk/promotions'
    | '/kk/stores'
    | '/kk/terms'
    | '/news/$slug'
    | '/promotions/$slug'
    | '/kk'
    | '/kk/catalog/$slug'
    | '/kk/news/$slug'
    | '/kk/promotions/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cake-preorder'
    | '/career'
    | '/catalog'
    | '/catering'
    | '/contacts'
    | '/news'
    | '/privacy'
    | '/promotions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stores'
    | '/terms'
    | '/catalog_/$slug'
    | '/kk/about'
    | '/kk/cake-preorder'
    | '/kk/career'
    | '/kk/catalog'
    | '/kk/catering'
    | '/kk/contacts'
    | '/kk/news'
    | '/kk/privacy'
    | '/kk/promotions'
    | '/kk/stores'
    | '/kk/terms'
    | '/news_/$slug'
    | '/promotions_/$slug'
    | '/kk/'
    | '/kk/catalog_/$slug'
    | '/kk/news_/$slug'
    | '/kk/promotions_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CakePreorderRoute: typeof CakePreorderRoute
  CareerRoute: typeof CareerRoute
  CatalogRoute: typeof CatalogRoute
  CateringRoute: typeof CateringRoute
  ContactsRoute: typeof ContactsRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  PromotionsRoute: typeof PromotionsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  TermsRoute: typeof TermsRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  KkAboutRoute: typeof KkAboutRoute
  KkCakePreorderRoute: typeof KkCakePreorderRoute
  KkCareerRoute: typeof KkCareerRoute
  KkCatalogRoute: typeof KkCatalogRoute
  KkCateringRoute: typeof KkCateringRoute
  KkContactsRoute: typeof KkContactsRoute
  KkNewsRoute: typeof KkNewsRoute
  KkPrivacyRoute: typeof KkPrivacyRoute
  KkPromotionsRoute: typeof KkPromotionsRoute
  KkStoresRoute: typeof KkStoresRoute
  KkTermsRoute: typeof KkTermsRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PromotionsSlugRoute: typeof PromotionsSlugRoute
  KkIndexRoute: typeof KkIndexRoute
  KkCatalogSlugRoute: typeof KkCatalogSlugRoute
  KkNewsSlugRoute: typeof KkNewsSlugRoute
  KkPromotionsSlugRoute: typeof KkPromotionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cake-preorder': {
      id: '/cake-preorder'
      path: '/cake-preorder'
      fullPath: '/cake-preorder'
      preLoaderRoute: typeof CakePreorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog_/$slug': {
      id: '/catalog_/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/': {
      id: '/kk/'
      path: '/kk'
      fullPath: '/kk/'
      preLoaderRoute: typeof KkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/about': {
      id: '/kk/about'
      path: '/kk/about'
      fullPath: '/kk/about'
      preLoaderRoute: typeof KkAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/cake-preorder': {
      id: '/kk/cake-preorder'
      path: '/kk/cake-preorder'
      fullPath: '/kk/cake-preorder'
      preLoaderRoute: typeof KkCakePreorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/career': {
      id: '/kk/career'
      path: '/kk/career'
      fullPath: '/kk/career'
      preLoaderRoute: typeof KkCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/catalog': {
      id: '/kk/catalog'
      path: '/kk/catalog'
      fullPath: '/kk/catalog'
      preLoaderRoute: typeof KkCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/catering': {
      id: '/kk/catering'
      path: '/kk/catering'
      fullPath: '/kk/catering'
      preLoaderRoute: typeof KkCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/contacts': {
      id: '/kk/contacts'
      path: '/kk/contacts'
      fullPath: '/kk/contacts'
      preLoaderRoute: typeof KkContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/news': {
      id: '/kk/news'
      path: '/kk/news'
      fullPath: '/kk/news'
      preLoaderRoute: typeof KkNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/privacy': {
      id: '/kk/privacy'
      path: '/kk/privacy'
      fullPath: '/kk/privacy'
      preLoaderRoute: typeof KkPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/promotions': {
      id: '/kk/promotions'
      path: '/kk/promotions'
      fullPath: '/kk/promotions'
      preLoaderRoute: typeof KkPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/stores': {
      id: '/kk/stores'
      path: '/kk/stores'
      fullPath: '/kk/stores'
      preLoaderRoute: typeof KkStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/terms': {
      id: '/kk/terms'
      path: '/kk/terms'
      fullPath: '/kk/terms'
      preLoaderRoute: typeof KkTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions_/$slug': {
      id: '/promotions_/$slug'
      path: '/promotions/$slug'
      fullPath: '/promotions/$slug'
      preLoaderRoute: typeof PromotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/catalog_/$slug': {
      id: '/kk/catalog_/$slug'
      path: '/kk/catalog/$slug'
      fullPath: '/kk/catalog/$slug'
      preLoaderRoute: typeof KkCatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/news_/$slug': {
      id: '/kk/news_/$slug'
      path: '/kk/news/$slug'
      fullPath: '/kk/news/$slug'
      preLoaderRoute: typeof KkNewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kk/promotions_/$slug': {
      id: '/kk/promotions_/$slug'
      path: '/kk/promotions/$slug'
      fullPath: '/kk/promotions/$slug'
      preLoaderRoute: typeof KkPromotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CakePreorderRoute: CakePreorderRoute,
  CareerRoute: CareerRoute,
  CatalogRoute: CatalogRoute,
  CateringRoute: CateringRoute,
  ContactsRoute: ContactsRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  PromotionsRoute: PromotionsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  TermsRoute: TermsRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  KkAboutRoute: KkAboutRoute,
  KkCakePreorderRoute: KkCakePreorderRoute,
  KkCareerRoute: KkCareerRoute,
  KkCatalogRoute: KkCatalogRoute,
  KkCateringRoute: KkCateringRoute,
  KkContactsRoute: KkContactsRoute,
  KkNewsRoute: KkNewsRoute,
  KkPrivacyRoute: KkPrivacyRoute,
  KkPromotionsRoute: KkPromotionsRoute,
  KkStoresRoute: KkStoresRoute,
  KkTermsRoute: KkTermsRoute,
  NewsSlugRoute: NewsSlugRoute,
  PromotionsSlugRoute: PromotionsSlugRoute,
  KkIndexRoute: KkIndexRoute,
  KkCatalogSlugRoute: KkCatalogSlugRoute,
  KkNewsSlugRoute: KkNewsSlugRoute,
  KkPromotionsSlugRoute: KkPromotionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
